require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable

Lint/MissingCopEnableDirective:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
