version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=rootbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgres/data

volumes:
  pg_data:
